version: '3.1'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress_aquarela
    ports:
      - '9000:80'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html # Synchronisation avec le dossier local
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    volumes:
      - ./db_data:/var/lib/mysql # Stockage persistant de la DB
    restart: always
